### ISSUE TITLE
could not create Vfs.Dir from url

### ISSUE THREAD

**Issue by WalterMourao** [joinfaces/joinfaces-example#96]
Hi folks.
Testing joinfaces-example 2.3.6 in a Ubuntu 17.04, Java 8, I've got:

```
2017-04-30 08:40:47.691  WARN 8301 --- [ost-startStop-1] org.reflections.Reflections              : could not create Vfs.Dir from url. ignoring the exception and continuing

org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:109) ~[reflections-0.9.10.jar!/:na]
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) ~[reflections-0.9.10.jar!/:na]
	at org.reflections.Reflections.scan(Reflections.java:237) [reflections-0.9.10.jar!/:na]
	at org.reflections.Reflections.scan(Reflections.java:204) [reflections-0.9.10.jar!/:na]
	at org.reflections.Reflections.<init>(Reflections.java:129) [reflections-0.9.10.jar!/:na]
	at org.joinfaces.JsfClassFactory.computeClasses(JsfClassFactory.java:185) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
	at org.joinfaces.JsfClassFactory.getAnnotatedClassMap(JsfClassFactory.java:157) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
	at org.joinfaces.JsfClassFactory.getAnnotatedClasses(JsfClassFactory.java:215) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
	at org.joinfaces.JsfClassFactory.getAllClasses(JsfClassFactory.java:204) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
	at org.joinfaces.mojarra.MojarraServletContextInitializer.onStartup(MojarraServletContextInitializer.java:76) [jsf-spring-boot-autoconfigure-2.3.6.jar!/:2.3.6]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:229) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:89) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:213) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:55) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

```
any hints?

**Comment by persapiens** [comment]
hi @WalterMourao , we are discussing this error [here.](https://github.com/joinfaces/joinfaces/issues/264)

**Comment by WalterMourao** [comment]
Thanks
